language: php
sudo: false
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
cache:
  directories:
  - vendor/
before_install:
  - composer self-update
before_script:
  - if [ ! -d "vendor/phpunit" ]; then composer install; fi
script: php vendor/bin/phpunit --colors --bootstrap vendor/autoload.php tests/